# Generated by Django 4.1.7 on 2023-09-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="name",
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
