# Generated by Django 4.1.7 on 2023-09-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_courses_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="module",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
